Repository polkadot-cloud/polkadot-staking-dashboard, pull requests merged in 2023-09, with the labels that each got.

#1417 Claim payout modal translations
  src/locale/cn/modals.json
  src/locale/en/modals.json
  src/modals/ClaimPayouts/Forms.tsx
  src/modals/ClaimPayouts/Item.tsx
  src/modals/ClaimPayouts/Overview.tsx
  src/modals/ClaimPayouts/index.tsx
Labels: 1.0.9

#1425 Move memberCount to context
  package.json
  src/Providers.tsx
  src/contexts/Pools/ActivePools/defaults.ts
  src/contexts/Pools/ActivePools/index.tsx
  src/contexts/Pools/types.ts
  src/pages/Pools/Home/Members.tsx
  src/pages/Pools/Home/PoolStats/index.tsx
  src/pages/Pools/Home/index.tsx
  yarn.lock
Labels: 1.0.9

#1430 Claim payout fixes
  src/contexts/Payouts/index.tsx
  src/locale/cn/modals.json
  src/locale/en/modals.json
  src/modals/ClaimPayouts/Overview.tsx
Labels: 1.0.9.1

#1444 Migrate `vite-plugin-svgr` to v4
  package.json
  src/config/ledger.ts
  src/config/networks.ts
  src/library/Modal/Close.tsx
  src/library/Modal/Title.tsx
  src/library/SideMenu/index.tsx
  src/modals/Accounts/Account.tsx
  src/modals/ChooseLanguage/index.tsx
  src/modals/Connect/Ledger.tsx
  src/modals/Connect/Vault.tsx
  src/modals/GoToFeedback/index.tsx
  src/modals/ImportLedger/Manage.tsx
  src/modals/ImportLedger/Splash.tsx
  src/modals/ImportVault/index.tsx
  src/modals/Networks/index.tsx
  yarn.lock
Labels: 1.1

#1445 Replace chart pie with the one from polkadot-cloud
  package.json
  src/library/Graphs/StatBoxPie.tsx
  src/library/Graphs/types.ts
  src/library/StatBoxList/Pie.tsx
  src/library/StatBoxList/Timeleft.tsx
  yarn.lock
Labels: 1.1

#1379 Polkawatch integration - Validator Decentralization Modal View
  package.json
  src/Providers.tsx
  src/config/help.ts
  src/consts.ts
  src/contexts/Plugins/Polkawatch/defaults.tsx
  src/contexts/Plugins/Polkawatch/index.tsx
  src/contexts/Plugins/Polkawatch/types.tsx
  src/library/Graphs/GeoDonut.tsx
  src/library/Graphs/types.ts
  src/library/PolkawatchButton/index.tsx
  src/library/PolkawatchButton/types.ts
  src/library/ValidatorList/Validator/Default.tsx
  src/locale/cn/help.json
  src/locale/cn/library.json
  src/locale/cn/modals.json
  src/locale/en/help.json
  src/locale/en/library.json
  src/locale/en/modals.json
  src/modals/Settings/index.tsx
  src/modals/ValidatorGeo/index.tsx
  src/overlay/index.tsx
  src/types/index.ts
  yarn.lock
Labels: 1.1

#1463 Misc Plugin tidy up
  src/Providers.tsx
  src/consts.ts
  src/contexts/Plugins/Polkawatch/defaults.tsx
  src/contexts/Plugins/Polkawatch/index.tsx
  src/contexts/Plugins/Subscan/defaults.ts
  src/contexts/Plugins/Subscan/index.tsx
  src/contexts/Plugins/Subscan/types.ts
  src/contexts/Plugins/index.tsx
  src/contexts/Plugins/types.ts
  src/contexts/Pools/ActivePools/index.tsx
  src/library/Graphs/PayoutBar.tsx
  src/library/Graphs/PayoutLine.tsx
  src/library/PluginLabel/Wrapper.ts
  src/library/PluginLabel/index.tsx
  src/library/PluginLabel/types.ts
  src/library/PolkawatchButton/index.tsx
  src/library/StatusLabel/index.tsx
  src/library/StatusLabel/types.ts
  src/library/SubscanButton/index.tsx
  src/library/SubscanButton/types.ts
  src/modals/ClaimPayouts/Forms.tsx
  src/modals/Settings/index.tsx
  src/modals/ValidatorGeo/index.tsx
  src/modals/ValidatorMetrics/index.tsx
  src/pages/Overview/index.tsx
  src/pages/Payouts/index.tsx
  src/pages/Pools/Home/MembersList/FetchPage.tsx
  src/types/index.ts
Labels: 1.1

#1464 Use cloud `ExtensionProvider`
  package.json
  src/Providers.tsx
  src/contexts/Connect/Hooks/useImportExtension.tsx
  src/contexts/Connect/Utils.ts
  src/contexts/Connect/index.tsx
  src/contexts/Connect/types.ts
  src/contexts/Extensions/defaults.ts
  src/contexts/Extensions/index.tsx
  src/contexts/Extensions/types.ts
  src/library/Form/types.ts
  src/library/Hooks/useSubmitExtrinsic/index.tsx
  src/modals/Accounts/index.tsx
  src/modals/Connect/Extension.tsx
  src/modals/Connect/index.tsx
  yarn.lock
Labels: 1.1
