Repository polkadot-cloud/polkadot-staking-dashboard, pull requests merged in 2023-02, with the labels that each got.

#626 Chores + Bonded Graphs to Bar Charts
  src/Utils.ts
  src/Wrappers.tsx
  src/index.css
  src/library/BarChart/BarSegment.tsx
  src/library/BarChart/BondedChart.tsx
  src/library/BarChart/LegendItem.tsx
  src/library/BarChart/Wrappers.ts
  src/library/BarChart/defaults.ts
  src/library/BarChart/types.ts
  src/library/Graphs/Bonded.tsx
  src/library/Headers/Connected.tsx
  src/library/Hooks/useSubmitExtrinsic/index.tsx
  src/library/Loaders/Announcement.tsx
  src/library/SetupSteps/Nominate.tsx
  src/library/Stat/Wrapper.ts
  src/library/Stat/index.tsx
  src/library/Stat/types.ts
  src/library/ValidatorList/Filters.tsx
  src/modals/ConnectAccounts/ReadOnlyInput/index.tsx
  src/modals/ManagePool/Forms.tsx
  src/modals/Networks/index.tsx
  src/pages/Nominate/Active/ManageBond.tsx
  src/pages/Nominate/Active/Status/Controller.tsx
  src/pages/Nominate/Active/Status/ControllerStatus.tsx
  src/pages/Nominate/Active/Status/NominationStatus.tsx
  src/pages/Nominate/Active/Status/PayoutDestinationStatus.tsx
  src/pages/Nominate/Active/Status/Wrappers.ts
  src/pages/Nominate/Active/Status/index.tsx
  src/pages/Nominate/Active/index.tsx
  src/pages/Nominate/Active/types.ts
  src/pages/Nominate/Setup/Bond/index.tsx
  src/pages/Nominate/Setup/Payee/index.tsx
  src/pages/Nominate/Setup/Summary/index.tsx
  src/pages/Overview/BalanceChart.tsx
  src/pages/Overview/NetworkSats/Announcements.tsx
  src/pages/Overview/StakeStatus/Item.tsx
  src/pages/Overview/StakeStatus/index.tsx
  src/pages/Pools/Create/Bond/index.tsx
  src/pages/Pools/Create/PoolName/Input.tsx
  src/pages/Pools/Create/PoolName/index.tsx
  src/pages/Pools/Create/PoolRoles/index.tsx
  src/pages/Pools/Create/Summary/index.tsx
  src/pages/Pools/Home/ManageBond.tsx
  src/pages/Pools/Home/PoolStats/Announcements.tsx
  src/pages/Pools/Home/Status/Membership/Wrapper.ts
  src/pages/Pools/Home/Status/Membership/index.tsx
  src/pages/Pools/Home/Status/MembershipStatus.tsx
  src/pages/Pools/Home/Status/PoolStatus.tsx
  src/pages/Pools/Home/Status/RewardsStatus.tsx
  src/pages/Pools/Home/Status/index.tsx
  src/pages/Pools/Home/Status/useStatusButtons.tsx
  src/pages/Pools/Home/index.tsx
  src/pages/Pools/Roles/RoleEditInput/index.tsx
Labels: v1.0.4

#613 Small fixes
  src/contexts/Api/defaults.ts
  src/contexts/Api/index.tsx
  src/contexts/Api/types.ts
  src/contexts/Staking/index.tsx
  src/library/Form/Bond/BondFeedback.tsx
  src/library/Form/Unbond/UnbondFeedback.tsx
  src/library/Form/types.ts
  src/library/Hooks/useErasToTimeLeft/index.tsx
  src/library/NetworkBar/Status.tsx
  src/library/SideMenu/index.tsx
  src/locale/cn/library.json
  src/locale/en/library.json
  src/modals/Bond/index.tsx
  src/modals/JoinPool/index.tsx
  src/modals/Unbond/index.tsx
  src/modals/UnlockChunks/Overview.tsx
  src/pages/Overview/Stats/ActiveEraTimeLeft.tsx
Labels: v1.0.4

#636 Update stakeworld stashes
  src/config/validators/index.ts
Labels: v1.0.4

#633 Transform era to date for modals
  src/library/Hooks/useErasToTimeLeft/index.tsx
  src/library/Hooks/useTimeLeft/defaults.ts
  src/library/Hooks/useTimeLeft/index.tsx
  src/library/Hooks/useTimeLeft/types.ts
  src/library/Hooks/useTimeLeft/utils.ts
  src/library/Stat/Wrapper.ts
  src/locale/cn/base.json
  src/locale/cn/modals.json
  src/locale/en/base.json
  src/locale/en/modals.json
  src/modals/LeavePool/index.tsx
  src/modals/Unbond/index.tsx
  src/modals/UnbondPoolMember/index.tsx
  src/modals/UnlockChunks/Overview.tsx
  src/modals/Unstake/index.tsx
Labels: v1.0.4

#652 Correct the epoch help definition
  src/locale/cn/help.json
  src/locale/en/help.json
Labels: documentation

#670 Introduce Array.at(index)
  src/contexts/FastUnstake/index.tsx
Labels: v1.0.5

#677 Get MinActiveStake from the API
  src/config/help.ts
  src/contexts/Network/defaults.ts
  src/contexts/Network/index.tsx
  src/contexts/Network/types.ts
  src/contexts/Staking/defaults.ts
  src/contexts/Staking/index.tsx
  src/contexts/Staking/types.ts
  src/library/Form/NominateStatusBar/index.tsx
  src/library/Hooks/useFillVariables/index.tsx
  src/locale/cn/help.json
  src/locale/cn/modals.json
  src/locale/cn/pages.json
  src/locale/cn/tips.json
  src/locale/en/help.json
  src/locale/en/pages.json
  src/locale/en/tips.json
  src/modals/UpdatePayee/index.tsx
  src/pages/Nominate/Active/Stats/MinimumActiveStake.tsx
  src/pages/Nominate/Active/index.tsx
  src/pages/Overview/NetworkSats/Announcements.tsx
  src/workers/stakers.ts
Labels: v1.0.5

#678 Add countdown timer in unlock chunk
  src/library/Countdown/index.tsx
  src/library/Countdown/types.ts
  src/library/StatBoxList/Wrapper.ts
  src/locale/cn/modals.json
  src/locale/en/modals.json
  src/modals/UnlockChunks/Chunk.tsx
  src/modals/UnlockChunks/Overview.tsx
  src/modals/UnlockChunks/index.tsx
Labels: v1.0.5

#697 timeleftAsString takes start time
  src/library/Hooks/useTimeLeft/utils.ts
  src/modals/LeavePool/index.tsx
  src/modals/Unbond/index.tsx
  src/modals/UnbondPoolMember/index.tsx
  src/modals/UnlockChunks/Overview.tsx
  src/modals/Unstake/index.tsx
Labels: v1.0.5

#701 Remove controller accounts from account selection
  src/modals/ConnectAccounts/Account.tsx
  src/modals/ConnectAccounts/Accounts.tsx
  src/modals/ConnectAccounts/Wrappers.ts
  src/modals/ConnectAccounts/types.ts
  src/pages/Overview/Stats/ActiveEraTimeLeft.tsx
Labels: v1.0.5

#659 Add unclaimed rewards to PayoutBar
  src/config/networks.ts
  src/contexts/Subscan/defaults.ts
  src/contexts/Subscan/index.tsx
  src/contexts/Subscan/types.ts
  src/library/Graphs/PayoutBar.tsx
  src/library/Graphs/PayoutLine.tsx
  src/library/Graphs/Utils.ts
  src/locale/cn/library.json
  src/locale/en/library.json
  src/pages/Overview/index.tsx
  src/types/index.ts
Labels: v1.0.5

#704 Replace OpenHelpIcon with ButtonHelp
  src/library/BarChart/LegendItem.tsx
  src/library/Form/NominateStatusBar/index.tsx
  src/library/Graphs/Wrappers.ts
  src/library/Modal/Title.tsx
  src/library/Modal/Wrappers.tsx
  src/library/OpenHelpIcon/Wrapper.tsx
  src/library/OpenHelpIcon/index.tsx
  src/library/OpenHelpIcon/types.ts
  src/library/Overlay/Title.tsx
  src/library/SetupSteps/Header/Wrapper.ts
  src/library/SetupSteps/Header/index.tsx
  src/library/Stat/Wrapper.ts
  src/library/Stat/index.tsx
  src/library/StatBoxList/Number.tsx
  src/library/StatBoxList/Pie.tsx
  src/library/StatBoxList/Text.tsx
  src/library/StatBoxList/Timeleft.tsx
  src/library/StatBoxList/Wrapper.ts
  src/library/StatusLabel/Wrapper.ts
  src/library/StatusLabel/index.tsx
  src/modals/ValidatorMetrics/index.tsx
  src/pages/Nominate/Active/ManageBond.tsx
  src/pages/Nominate/Active/Nominations/index.tsx
  src/pages/Nominate/Active/index.tsx
  src/pages/Overview/NetworkSats/Header.tsx
  src/pages/Overview/NetworkSats/Wrappers.ts
  src/pages/Overview/NetworkSats/index.tsx
  src/pages/Payouts/index.tsx
  src/pages/Pools/Home/ManageBond.tsx
  src/pages/Pools/Home/ManagePool/Wrappers.tsx
  src/pages/Pools/Home/ManagePool/index.tsx
  src/pages/Pools/Home/PoolStats/Wrappers.ts
  src/pages/Pools/Roles/index.tsx
Labels: v1.0.5
