Repository polkadot-cloud/polkadot-staking-dashboard, pull requests merged in 2023-06, with the labels that each got.

#1072 Account Button Refactor
  src/library/Account/index.tsx
  src/library/Headers/Connect.tsx
  src/library/Headers/Wrappers.ts
  src/library/PoolAccount/index.tsx
Labels: 1.0.8

#1076 Add OpenGov Delegation Dashboard app banner
  src/library/SideMenu/Main.tsx
  src/locale/cn/pages.json
  src/locale/en/pages.json
  src/pages/Overview/Wrappers.ts
  src/pages/Overview/index.tsx
Labels: 1.0.8

#1077 Make hardware StatusBar reusable
  src/library/Import/StatusBar.tsx
  src/library/Import/types.ts
  src/modals/ImportLedger/Manage.tsx
  src/modals/ImportVault/index.tsx
Labels: 1.0.8

#1078 Iterate hardware Address
  src/library/Import/Address.tsx
  src/library/Import/Wrappers.ts
  src/library/Import/types.ts
  src/modals/ImportLedger/Addresses.tsx
  src/modals/ImportVault/index.tsx
Labels: 1.0.8

#1080 Add Inter Bold Font
  package.json
  src/library/BarChart/Wrappers.ts
  src/library/Graphs/Wrappers.ts
  src/library/List/index.ts
  src/library/PoolAccount/Wrapper.ts
  src/library/SelectItems/Wrapper.ts
  src/library/SideMenu/Primary/Wrappers.tsx
  src/library/SideMenu/Secondary/Wrappers.tsx
  src/library/Stat/Wrapper.ts
  src/library/StatBoxList/Wrapper.ts
  src/pages/Overview/ActiveAccounts/Wrappers.ts
  src/pages/Overview/StakeStatus/Item.tsx
  src/pages/Overview/StakeStatus/Tips/Wrappers.tsx
  src/pages/Overview/StakeStatus/Wrappers.tsx
  src/pages/Pools/Home/ManagePool/Wrappers.tsx
  src/pages/Pools/PoolAccount/Wrapper.tsx
  yarn.lock
Labels: 1.0.8

#1082 Use HardwareAddress, spacing amendments
  package.json
  src/library/BarChart/Wrappers.ts
  src/library/Graphs/Wrappers.ts
  src/library/Import/Address.tsx
  src/library/Import/Wrappers.ts
  src/modals/ImportLedger/Addresses.tsx
  src/modals/ImportVault/index.tsx
  src/pages/Nominate/Active/index.tsx
  src/pages/Nominate/Setup/index.tsx
  src/pages/Overview/NetworkSats/Wrappers.ts
  src/pages/Overview/StakeStatus/Tips/Wrappers.tsx
  src/pages/Overview/StakeStatus/Wrappers.tsx
  src/pages/Overview/Wrappers.ts
  src/pages/Pools/Create/index.tsx
  src/pages/Pools/Home/PoolStats/Wrappers.ts
  src/pages/Pools/Home/index.tsx
  yarn.lock
Labels: 1.0.8

#1084 Add StatsHead, rm duplicates
  src/library/StatsHead/Wrapper.ts
  src/library/StatsHead/index.tsx
  src/library/StatsHead/types.ts
  src/pages/Overview/NetworkSats/Header.tsx
  src/pages/Overview/NetworkSats/Wrappers.ts
  src/pages/Overview/NetworkSats/index.tsx
  src/pages/Pools/Home/PoolStats/Header.tsx
  src/pages/Pools/Home/PoolStats/Wrappers.ts
  src/pages/Pools/Home/PoolStats/index.tsx
Labels: 1.0.8

#1081 Add Fee Reserve Feature
  package.json
  src/config/help.ts
  src/contexts/TransferOptions/defaults.ts
  src/contexts/TransferOptions/index.tsx
  src/contexts/TransferOptions/types.ts
  src/library/Hooks/useBondGreatestFee/index.tsx
  src/locale/cn/help.json
  src/locale/cn/modals.json
  src/locale/cn/pages.json
  src/locale/en/help.json
  src/locale/en/modals.json
  src/locale/en/pages.json
  src/modals/Bond/index.tsx
  src/modals/ManageFastUnstake/index.tsx
  src/modals/ManagePool/Forms/Commission.tsx
  src/modals/ManagePool/Wrappers.ts
  src/modals/UpdateReserve/index.tsx
  src/modals/index.tsx
  src/pages/Overview/BalanceChart.tsx
  src/pages/Overview/BalanceLinks.tsx
  src/pages/Overview/StakeStatus/Tips/index.tsx
  src/pages/Overview/Wrappers.ts
  yarn.lock
Labels: 1.0.8

#1103 Commission subtitle
  src/library/AccountInput/Wrapper.ts
  src/library/AccountInput/index.tsx
  src/library/AccountInput/types.ts
  src/library/Form/MinDelayInput/Wrapper.ts
  src/locale/cn/modals.json
  src/locale/en/modals.json
  src/modals/ManagePool/Forms/Commission.tsx
  src/modals/ManagePool/Wrappers.ts
Labels: 1.0.8

#1106 1.0.8 Pre-Release Fixes & Optimisations
  src/library/Hooks/useBatchCall/index.tsx
  src/library/Hooks/useBuildPayload/index.tsx
  src/library/Hooks/useProxySupported/index.tsx
  src/library/Hooks/useSubmitExtrinsic/index.tsx
  src/library/Import/Wrappers.ts
  src/library/SubmitTx/ManualSign/index.tsx
  src/modals/BalanceTest/index.tsx
  src/modals/ImportVault/Reader.tsx
  src/modals/JoinPool/index.tsx
  src/modals/ManagePool/Forms/Commission.tsx
  src/modals/Unstake/index.tsx
  src/modals/UpdateReserve/index.tsx
  src/pages/Nominate/Setup/Summary/index.tsx
  src/pages/Pools/Create/Summary/index.tsx
Labels: 1.0.8

#1107 Add defaultFeeReserve
  src/config/networks.ts
  src/contexts/TransferOptions/index.tsx
  src/types/index.ts
Labels: 1.0.8

#1111 expand ActiveProxy & Migrate
  src/contexts/Connect/index.tsx
  src/contexts/Connect/types.ts
  src/contexts/Migrate/index.tsx
  src/contexts/Proxies/index.tsx
  src/modals/Accounts/Account.tsx
  src/modals/Accounts/Delegates.tsx
  src/modals/Accounts/types.ts
Labels: 1.0.8

#1112 Add nesting error to ledger feedback
  src/contexts/Hardware/Ledger.tsx
  src/contexts/Hardware/types.ts
  src/locale/cn/modals.json
  src/locale/en/modals.json
Labels: needs-translations, 1.0.8

#1113 Connect to account on page load with `a` URL variable
  README.md
  src/Router.tsx
  src/contexts/Connect/defaults.ts
  src/contexts/Connect/index.tsx
  src/contexts/Connect/types.ts
  src/contexts/Extensions/index.tsx
  src/locale/cn/library.json
  src/locale/en/library.json
Labels: 1.0.9

#1130 9420 Runtime Fixes
  src/contexts/Balances/index.tsx
  src/contexts/Pools/ActivePools/defaults.ts
  src/contexts/Pools/ActivePools/index.tsx
  src/contexts/Pools/BondedPools/index.tsx
  src/contexts/Pools/PoolsConfig/defaults.ts
  src/contexts/Pools/PoolsConfig/index.tsx
  src/contexts/Pools/types.ts
  src/locale/cn/help.json
  src/locale/cn/modals.json
  src/locale/cn/pages.json
  src/locale/en/help.json
  src/locale/en/modals.json
  src/locale/en/pages.json
  src/modals/AccountPoolRoles/index.tsx
  src/modals/ChangePoolRoles/index.tsx
  src/modals/ManagePool/Forms/Commission.tsx
  src/modals/ManagePool/Forms/SetState.tsx
  src/modals/ManagePool/Tasks.tsx
  src/pages/Pools/Create/PoolRoles/index.tsx
  src/pages/Pools/Create/Summary/index.tsx
  src/pages/Pools/Home/Members.tsx
  src/pages/Pools/Home/MembersList/Member.tsx
  src/pages/Pools/Home/Status/MembershipStatus.tsx
  src/pages/Pools/Roles/index.tsx
  yarn.lock
Labels: pending-deploy, 1.0.8.1

#1158 Use transient props for bools for styled components
  src/library/Account/Wrapper.ts
  src/library/Account/index.tsx
  src/library/Account/types.ts
  src/library/BarChart/BondedChart.tsx
  src/library/BarChart/Wrappers.ts
  src/library/Card/Wrappers.ts
  src/library/Filter/Tabs.tsx
  src/library/Filter/Wrappers.ts
  src/library/Form/ClaimPermissionInput/index.tsx
  src/library/Graphs/types.ts
  src/library/List/Pagination.tsx
  src/library/List/index.ts
  src/library/List/types.ts
  src/library/Modal/Title.tsx
  src/library/Modal/Wrappers.tsx
  src/library/Overlay/Wrappers.tsx
  src/library/PayeeInput/Wrapper.ts
  src/library/PayeeInput/index.tsx
  src/library/PoolAccount/Wrapper.ts
  src/library/PoolAccount/index.tsx
  src/library/PoolAccount/types.ts
  src/library/SelectItems/Item.tsx
  src/library/SelectItems/Wrapper.ts
  src/library/SideMenu/Main.tsx
  src/library/SideMenu/Wrapper.ts
  src/library/SideMenu/index.tsx
  src/library/SideMenu/types.ts
  src/library/Stat/Wrapper.ts
  src/library/Stat/index.tsx
  src/library/StatBoxList/Text.tsx
  src/library/StatBoxList/Wrapper.ts
  src/library/ValidatorList/FilterValidators.tsx
  src/library/ValidatorList/OrderValidators.tsx
  src/modals/ValidatorMetrics/index.tsx
  src/pages/Nominate/Active/ControllerNotStash.tsx
  src/pages/Nominate/Active/Nominations/index.tsx
  src/pages/Nominate/Active/index.tsx
  src/pages/Nominate/Wrappers.tsx
  src/pages/Overview/StakeStatus/index.tsx
  src/pages/Overview/index.tsx
  src/pages/Pools/Home/ManagePool/index.tsx
  src/pages/Pools/PoolAccount/Wrapper.tsx
  src/pages/Pools/PoolAccount/index.tsx
  src/pages/Pools/Roles/index.tsx
  src/pages/Pools/types.ts
Labels: 1.0.9
